chore(package): update @effect/schema to 0.68.16
- [#3143](https://github.com/Effect-TS/effect/pull/3143) [`d006cec`](https://github.com/Effect-TS/effect/commit/d006cec022e8524dbfd6dc6df751fe4c86b10042) - Enhance JSON Schema Support for Refinements in Record Parameters.

  Enhanced `JSONSchema.make` to properly support refinements as record parameters. Previously, using refinements with `Schema.Record` resulted in errors when generating JSON schemas.

  Before

  ```ts
  import { JSONSchema, Schema } from "@effect/schema"

  const schema = Schema.Record(
    Schema.String.pipe(Schema.minLength(1)),
    Schema.Number
  )

  console.log(JSONSchema.make(schema))
  /*
  throws
  Error: Unsupported index signature parameter
  schema (Refinement): a string at least 1 character(s) long
  */
  ```

  Now

  ```ts
  import { JSONSchema, Schema } from "@effect/schema"

  const schema = Schema.Record(
    Schema.String.pipe(Schema.minLength(1)),
    Schema.Number
  )

  console.log(JSONSchema.make(schema))
  /*
  Output:
  {
    '$schema': 'http://json-schema.org/draft-07/schema#',
    type: 'object',
    required: [],
    properties: {},
    patternProperties: { '': { type: 'number' } },
    propertyNames: {
      type: 'string',
      description: 'a string at least 1 character(s) long',
      minLength: 1
    }
  }
  */
  ```

- [#3149](https://github.com/Effect-TS/effect/pull/3149) [`cb22726`](https://github.com/Effect-TS/effect/commit/cb2272656881aa5878a1c3fc0b12d8fbc66eb63c) - add Serializable.WithResult.Success/Error inference helpers

- [#3139](https://github.com/Effect-TS/effect/pull/3139) [`e911cfd`](https://github.com/Effect-TS/effect/commit/e911cfdc79418462d7e9000976fded15ea6b738d) - Optimize JSON Schema output for homogeneous tuples (such as non empty arrays).

  This change corrects the JSON Schema generation for `S.NonEmptyArray` to eliminate redundant schema definitions. Previously, the element schema was unnecessarily duplicated under both `items` and `additionalItems`.

Signed-off-by: Giovanni Ravalico <15946771+suddenlyGiovanni@users.noreply.github.com>